### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by rschwess** [KlugerLab/Ritornello#1]
Hi Guys,

Very much interested to try out you new caller.

When trying to compile it on Ubuntu (x64) and following your instructions I run into the error below.

Would Appreciate any help!

Cheers,
Ron

====================================================================

ron@ron-XPS:~/Data/tool_test/Ritornello$ make
g++ -Wall -fmessage-length=0 -O3 -DNDEBUG -DBOOST_UBLAS_NDEBUG -fopenmp -c -o bin/DepthGraph.o src/DepthGraph.cpp -I include/ -I /usr/include/samtools/ -I ~/fftw3Installation/include/ -I ~/samtools-0.1.19/		
g++ -Wall -fmessage-length=0 -O3 -DNDEBUG -DBOOST_UBLAS_NDEBUG -fopenmp -c -o bin/IOhandler.o src/IOhandler.cpp -I include/ -I /usr/include/samtools/ -I ~/fftw3Installation/include/ -I ~/samtools-0.1.19/		
g++ -Wall -fmessage-length=0 -O3 -DNDEBUG -DBOOST_UBLAS_NDEBUG -fopenmp -c -o bin/FLD.o src/FLD.cpp -I include/ -I /usr/include/samtools/ -I ~/fftw3Installation/include/ -I ~/samtools-0.1.19/		
g++ -Wall -fmessage-length=0 -O3 -DNDEBUG -DBOOST_UBLAS_NDEBUG -fopenmp -c -o bin/BufferedDepthGraphReader.o src/BufferedDepthGraphReader.cpp -I include/ -I /usr/include/samtools/ -I ~/fftw3Installation/include/ -I ~/samtools-0.1.19/		
g++ -Wall -fmessage-length=0 -O3 -DNDEBUG -DBOOST_UBLAS_NDEBUG -fopenmp -c -o bin/FIR.o src/FIR.cpp -I include/ -I /usr/include/samtools/ -I ~/fftw3Installation/include/ -I ~/samtools-0.1.19/		
g++ -Wall -fmessage-length=0 -O3 -DNDEBUG -DBOOST_UBLAS_NDEBUG -fopenmp -c -o bin/Peaks.o src/Peaks.cpp -I include/ -I /usr/include/samtools/ -I ~/fftw3Installation/include/ -I ~/samtools-0.1.19/		
g++ -Wall -fmessage-length=0 -O3 -DNDEBUG -DBOOST_UBLAS_NDEBUG -fopenmp -c -o bin/Main.o src/Main.cpp -I include/ -I /usr/include/samtools/ -I ~/fftw3Installation/include/ -I ~/samtools-0.1.19/		
g++ -Wall -fmessage-length=0 -O3 -DNDEBUG -DBOOST_UBLAS_NDEBUG -fopenmp -c -o bin/SamStream.o src/SamStream.cpp -I include/ -I /usr/include/samtools/ -I ~/fftw3Installation/include/ -I ~/samtools-0.1.19/		
g++ -Wall -fmessage-length=0 -O3 -DNDEBUG -DBOOST_UBLAS_NDEBUG -fopenmp -c -o bin/Ritornello.o src/Ritornello.cpp -I include/ -I /usr/include/samtools/ -I ~/fftw3Installation/include/ -I ~/samtools-0.1.19/		
g++ -Wall -fmessage-length=0 -O3 -DNDEBUG -DBOOST_UBLAS_NDEBUG -fopenmp -c -o bin/Config.o src/Config.cpp -I include/ -I /usr/include/samtools/ -I ~/fftw3Installation/include/ -I ~/samtools-0.1.19/		
g++ -Wall -fmessage-length=0 -O3 -DNDEBUG -DBOOST_UBLAS_NDEBUG -fopenmp -c -o bin/Artifact.o src/Artifact.cpp -I include/ -I /usr/include/samtools/ -I ~/fftw3Installation/include/ -I ~/samtools-0.1.19/		
g++ -Wall -fmessage-length=0 -O3 -DNDEBUG -DBOOST_UBLAS_NDEBUG -fopenmp -c -o bin/FFTHandler.o src/FFTHandler.cpp -I include/ -I /usr/include/samtools/ -I ~/fftw3Installation/include/ -I ~/samtools-0.1.19/		
g++ -Wall -fmessage-length=0 -O3 -DNDEBUG -DBOOST_UBLAS_NDEBUG -fopenmp -c -o bin/LikelihoodRatioTest.o src/LikelihoodRatioTest.cpp -I include/ -I /usr/include/samtools/ -I ~/fftw3Installation/include/ -I ~/samtools-0.1.19/		
src/LikelihoodRatioTest.cpp: In function ‘double lPois(long int, double)’:
src/LikelihoodRatioTest.cpp:190:34: error: call of overloaded ‘lgamma(long int)’ is ambiguous
  return k*log(mu) -mu -lgamma(k+1);
                                  ^
In file included from /usr/include/features.h:364:0,
                 from /usr/include/x86_64-linux-gnu/c++/6/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/6/bits/c++config.h:507,
                 from /usr/include/c++/6/cstddef:49,
                 from /usr/include/boost/config/compiler/gcc.hpp:165,
                 from /usr/include/boost/config.hpp:39,
                 from /usr/include/boost/numeric/ublas/matrix.hpp:17,
                 from src/LikelihoodRatioTest.h:10,
                 from src/LikelihoodRatioTest.cpp:7:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:261:1: note: candidate: double lgamma(double)
 __MATHCALL (lgamma,, (_Mdouble_));
 ^
In file included from /usr/include/c++/6/complex:44:0,
                 from /usr/include/boost/numeric/ublas/traits.hpp:17,
                 from /usr/include/boost/numeric/ublas/storage.hpp:26,
                 from /usr/include/boost/numeric/ublas/vector.hpp:21,
                 from /usr/include/boost/numeric/ublas/matrix.hpp:18,
                 from src/LikelihoodRatioTest.h:10,
                 from src/LikelihoodRatioTest.cpp:7:
/usr/include/c++/6/cmath:1543:5: note: candidate: constexpr typename __gnu_cxx::__enable_if<std::__is_integer<_Tp>::__value, double>::__type std::lgamma(_Tp) [with _Tp = long int; typename __gnu_cxx::__enable_if<std::__is_integer<_Tp>::__value, double>::__type = double]
     lgamma(_Tp __x)
     ^~~~~~
/usr/include/c++/6/cmath:1535:3: note: candidate: constexpr long double std::lgamma(long double)
   lgamma(long double __x)
   ^~~~~~
/usr/include/c++/6/cmath:1531:3: note: candidate: constexpr float std::lgamma(float)
   lgamma(float __x)
   ^~~~~~
In file included from /usr/include/boost/math/distributions/poisson.hpp:40:0,
                 from src/LikelihoodRatioTest.cpp:10:
/usr/include/boost/math/special_functions/gamma.hpp:1849:4: note: candidate: typename boost::math::tools::promote_args<T>::type boost::math::lgamma(RT) [with RT = long int; typename boost::math::tools::promote_args<T>::type = double]
    lgamma(T x)
    ^~~~~~
Makefile:29: recipe for target 'bin/LikelihoodRatioTest.o' failed
make: *** [bin/LikelihoodRatioTest.o] Error 1

======================================================================

**Comment by kstant0725** [comment]
Hello Ron,

Thank you for your interest in our software.  At first glance it looks like
the lgamma function from boost is ambiguously defined.  I am currently out
of the office until Monday but I will look into and get back to you once I
get back.

Best,
Kelly

**Comment by kstant0725** [comment]
Hello Ron,

I have followed up on the error.  It looks like on your system there is a collision between the lgamma function defined in the math.h and the boost library in the LikelihoodRatioTest.cpp file.  I am not sure why the collision doesn't happen on my system.

I committed a fix by explicitly specifying to use the boost namespace to avoid the collision.  Please do a pull or a clone and let me know if it will compile on your system now.

Best,
Kelly

**Comment by rschwess** [comment]
Compiled like a charm! Thanks

**Comment by kstant0725** [comment]
Awesome!  glad it worked
