### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by ChiWPak** [KlugerLab/Ritornello#2]
Hi:

I'm running into a `Segmentation fault` error - any idea what might be causing the issue?

```
$ Ritornello -f File.bam
Converting sam file to depth graph
Segmentation fault
```

The `File.bam` is 476 MB and I'm working with 256 GB RAM.

**Comment by kstant0725** [comment]
I'm not sure what would cause this.  Would you be able to send me some data
that causes the crash?

On Jul 20, 2018 2:57 PM, "Chi W Pak" <notifications@github.com> wrote:

Hi:

I'm running into a Segmentation fault error - any idea what might be
causing the issue?

$ Ritornello -f File.bam
Converting sam file to depth graph
Segmentation fault

The File.bam is 476 MB and I'm working with 256 GB RAM.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KlugerLab/Ritornello/issues/2>, or mute the thread

**Comment by ChiWPak** [comment]
What's a good way to share the data? Google Drive link ok?

**Comment by kstant0725** [comment]
Yeah that should work

**Comment by ChiWPak** [comment]
https://drive.google.com/open?id=1oMigRai-uIpbnoWvISoY454tUMMb4jvM

I'll remove it from my Drive once you've downloaded it. Thanks!

**Comment by kstant0725** [comment]
Awesome.  I just downloaded it so you can remove it.  I'll let you know
once I figure out the problem.

**Comment by ChiWPak** [comment]
Thanks for looking into it. It may be that I'm doing something stupid...

**Comment by kstant0725** [comment]
No problem, I probably won't get to it too the weekend though.

**Comment by ChiWPak** [comment]
Hi: Just following up - were you able to find time to look into the issue?

**Comment by kstant0725** [comment]
Hello Chi,

I think I found what was causing the fault but haven't had time correct it
yet.  Apologies for the late response.  I moved on to an industry job so I
mostly have nights and weekends to work on my research.  I should have more
time to work on it on the plane this weekend.  I will keep you updated once
I check in a fix.

Best,
Kelly

**Comment by ChiWPak** [comment]
> I think I found what was causing the fault but haven't had time correct it yet. Apologies for the late response.

Nice and No worries

> I moved on to an industry job

Thanks for providing support still. Didn't realize this was not your primary responsibility - take all the time you require.

**Comment by kstant0725** [comment]
So it seems as though the binary attached to the release might have been out of date.  The segmentation fault didn't occur with the most recent build so I created a new release with this build.  Please download and use this new version.  The output on your bam file should like like the following:

Converting sam file to depth graph
closing sam file
Finished converting sam file to depth graph
PCR correcting depth graph
Finished PCR correcting depth graph
Scanning genome
|------------------------|
*************************
Max fragment length set to [510]
Estimated maximum fragment length [510 bp]
Calculating median non-zero reads per window
Scanning genome
|------------------------|
*************************
Calculated median non-zero reads per window=[4]
Looking for candidate peaks
Scanning genome
|------------------------|
*************************
[484] candidate peaks found from local maxima after scanning [226113] positions
Testing peaks for artifacts and significance
|--------------------------------------------------------------------------------------------------|
****************************************************************************************************
Non-convergent likelihood tests[0]
[392] read length Artifacts found
Finished analyzing all Chromosomes found [92] candidate peaks
Sorting by log ratio test p-value
Applying Benjamini Hochberg
[3] Peaks are significant after multiple hypothesis correction
Sorting by effect size
Sorting by pvalue
Parameterizing alpha
Best alpha parameter is [1.000000]
K ~ Beta(alpha,alpha), alpha parameter=[1.000000]
Looking for candidate peaks
Scanning genome
|------------------------|
*************************
[2101] candidate peaks found from local maxima after scanning [4751842] positions
Testing peaks for artifacts and significance
|--------------------------------------------------------------------------------------------------|
****************************************************************************************************
Non-convergent likelihood tests[1]
[941] read length Artifacts found
Finished analyzing all Chromosomes found [1160] candidate peaks
Sorting by log ratio test p-value
Applying Benjamini Hochberg
[3] Peaks are significant after multiple hypothesis correction
Writing results to [/home/kelly/git/Ritornello/data/SRR061744_ScRFSc.bam-peakSummary.narrowPeak]
Writing artifacts to [/home/kelly/git/Ritornello/data/SRR061744_ScRFSc.bam-artifactSummary.bed]
Finished!!!

**Comment by ChiWPak** [comment]
Thanks for looking into it and resolving the issue. Just to be clear - do you mean this [build](https://github.com/KlugerLab/Ritornello/releases/tag/v2.0.1)? Thanks again!

**Comment by kstant0725** [comment]
This release v2.0.1 yes
